apiVersion: v1
kind: Service
metadata:
  name: app-template
  labels:
    app.kubernetes.io/name: app-template
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-template
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
