apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pipeline-serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml

configMapGenerator:
  - name: drone-runner-policy
    files:
      - policy.yml
